import "bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import "font-awesome/css/font-awesome.min.css";
import "./../vendors/animate.css";
import "./../../assets/scss/admin.scss";
import "./../vendors/animsition.min.js"
import "./../vendors/Chart.bundle.min.js"
import "./../../assets/js/dashboard.js";
import "./../../assets/js/app_admin.js";
import "./../../assets/js/app_user.js";
